# image will be published to ghcr.io/<user>/<name>
name: os
# description will be included in the image's metadata
description: Meu OS baseado do Fedora Silverblue.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: components/packages.yml

  - from-file: components/bling.yml

  - from-file: components/scripts.yml
  
  - from-file: components/fonts.yml

  - from-file: components/flatpak.yml

  - from-file: components/gnome-extensions.yml

  - from-file: components/files.yml

  - from-file: components/systemd.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

