default:
  @just --list

bios:
  systemctl reboot --firmware-setup

changelogs:
  rpm-ostree db diff --changelogs

boxkit:
  echo 'Criando boxkit...'
  distrobox create -a "--env SHELL=/bin/fish" -n arch -Y

update:
  #!/bin/bash
  echo "Atualizando o sistema..."
  rpm-ostree update

  echo "Atualizando flatpaks..."
  flatpak update -y

  echo "Atualizando distroboxes..."
  distrobox upgrade -a